### ISSUE TITLE
Please add screenshots/pics to README

### ISSUE THREAD

**Issue by luzpaz** [benjaminwand/3d-printed-labial-pipe#1]

**Comment by benjaminwand** [comment]
I’m assuming that I’m addressing people here (on GitHub) who are able to install FreeCAD and look at the actual files. Everyone else can go to https://www.thingiverse.com/thing:2745939

**Comment by luzpaz** [comment]
people search FC related things on github. But it's your call. Do you mind adding 'topics' aka tags to this repo? at least adding `freecad` ?

**Comment by benjaminwand** [comment]
ok. question: why are you trying to make me do these things?

**Comment by luzpaz** [comment]
I volunteer for FreeCAD and am trying to make searching FreeCAD related repos more search-able per se. I also keep an eye out for cool FC projects to share with the community

**Comment by benjaminwand** [comment]
How do you prefer FreeCAD-Projects to be presented on GitHub, what would be a good example in your opinion?
I didn’t post images because I think they aren’t necessary in the case of this repo. Sometimes they are to make a thing clear, like this https://github.com/benjaminwand/voctoknopf1/blob/master/photos%20%26%20co/bugfixes.jpg
Organ building is an incredibly nerdy topic, if someone in into organs *and* on GitHub, I’m pretty sure they can look at the files in FreeCAD on their own.

**Comment by luzpaz** [comment]
@benjaminwand First, Nerdy or not, it's cool and it was made using FC. I think it also merits being posted in the [User Showcase subforum](https://forum.freecadweb.org/viewforum.php?f=24).  
As for a good/ideal example, I will find you one soon.

**Comment by benjaminwand** [comment]
What is the purpose of the showcase forum?

Von meinem iPod gesendet

**Comment by luzpaz** [comment]
just to give a heads up to the FC community about a project and how FreeCAD was used for it.

**Comment by luzpaz** [comment]
apropos: https://forum.freecadweb.org/viewtopic.php?f=24&t=26319&p=208838#p208838

**Comment by benjaminwand** [comment]
https://forum.freecadweb.org/viewtopic.php?f=24&t=26464&p=210695#p210695
Are you happy now?

**Comment by benjaminwand** [comment]
It does not represent all the versions but I'm _really_ not willing to maintain a folder with screenshots of everything

**Comment by luzpaz** [comment]
fair enough. cheers
